---
name: CO
molecule_file: "Data/MoleculeData/NOData.txt"
partfun_file: 'Data/Partfuncs/Partfun_12C16O.txt'
temperature: 296  # Kelvin
mass: 28  # Molecular Mass
PTorr: 100  # Total pressure
PTorr_M: 1  # Species partial pressure
length: 10  # Absorption path cm
nu0: 1700  # Wavenumber lower bound
nuf: 1800  # Wavenumber upper bound
...
